-- 題庫與關卡目錄。schema.sql 跑完之後跑這一份。
-- 這份是 data/core300.json 與 src/data/levels.ts 產生出來的，不要手改。
-- 重跑會覆蓋成最新的內容，不會動到學生資料。

begin;

insert into public.words (id, word, pos, zh, theme, emoji, spell, level) values
  (1, 'zero', 'num.', '零', 'numbers', '0️⃣', true, 1),
  (2, 'one', 'num.', '一', 'numbers', '1️⃣', true, 1),
  (3, 'two', 'num.', '二', 'numbers', '2️⃣', true, 1),
  (4, 'three', 'num.', '三', 'numbers', '3️⃣', true, 1),
  (5, 'four', 'num.', '四', 'numbers', '4️⃣', true, 1),
  (6, 'five', 'num.', '五', 'numbers', '5️⃣', true, 1),
  (7, 'six', 'num.', '六', 'numbers', '6️⃣', true, 1),
  (8, 'seven', 'num.', '七', 'numbers', '7️⃣', true, 1),
  (9, 'eight', 'num.', '八', 'numbers', '8️⃣', true, 1),
  (10, 'nine', 'num.', '九', 'numbers', '9️⃣', true, 1),
  (11, 'ten', 'num.', '十', 'numbers', '🔟', true, 1),
  (12, 'eleven', 'num.', '十一', 'numbers', '🔢', true, 2),
  (13, 'twelve', 'num.', '十二', 'numbers', '🔢', true, 2),
  (14, 'thirteen', 'num.', '十三', 'numbers', '🔢', false, 3),
  (15, 'fourteen', 'num.', '十四', 'numbers', '🔢', false, 3),
  (16, 'fifteen', 'num.', '十五', 'numbers', '🔢', false, 3),
  (17, 'sixteen', 'num.', '十六', 'numbers', '🔢', false, 3),
  (18, 'seventeen', 'num.', '十七', 'numbers', '🔢', false, 3),
  (19, 'eighteen', 'num.', '十八', 'numbers', '🔢', false, 3),
  (20, 'nineteen', 'num.', '十九', 'numbers', '🔢', false, 3),
  (21, 'twenty', 'num.', '二十', 'numbers', '🔢', false, 3),
  (22, 'red', 'adj.', '紅色的', 'colors', '🔴', true, 1),
  (23, 'blue', 'adj.', '藍色的', 'colors', '🔵', true, 1),
  (24, 'yellow', 'adj.', '黃色的', 'colors', '🟡', true, 2),
  (25, 'green', 'adj.', '綠色的', 'colors', '🟢', true, 1),
  (26, 'black', 'adj.', '黑色的', 'colors', '⚫', true, 1),
  (27, 'white', 'adj.', '白色的', 'colors', '⚪', true, 2),
  (28, 'orange', 'adj.', '橘色的', 'colors', '🟠', true, 2),
  (29, 'purple', 'adj.', '紫色的', 'colors', '🟣', true, 2),
  (30, 'brown', 'adj.', '咖啡色的', 'colors', '🟤', true, 1),
  (31, 'pink', 'adj.', '粉紅色的', 'colors', '🌸', true, 1),
  (32, 'animal', 'n.', '動物', 'animals', '🐾', false, 2),
  (33, 'dog', 'n.', '狗', 'animals', '🐶', true, 1),
  (34, 'cat', 'n.', '貓', 'animals', '🐱', true, 1),
  (35, 'bird', 'n.', '鳥', 'animals', '🐦', true, 1),
  (36, 'fish', 'n.', '魚', 'animals', '🐟', true, 1),
  (37, 'pig', 'n.', '豬', 'animals', '🐷', true, 1),
  (38, 'cow', 'n.', '牛', 'animals', '🐮', true, 1),
  (39, 'horse', 'n.', '馬', 'animals', '🐴', true, 1),
  (40, 'sheep', 'n.', '綿羊', 'animals', '🐑', false, 2),
  (41, 'duck', 'n.', '鴨子', 'animals', '🦆', true, 1),
  (42, 'chicken', 'n.', '雞', 'animals', '🐔', false, 3),
  (43, 'rabbit', 'n.', '兔子', 'animals', '🐰', false, 2),
  (44, 'mouse', 'n.', '老鼠', 'animals', '🐭', false, 2),
  (45, 'bear', 'n.', '熊', 'animals', '🐻', true, 1),
  (46, 'lion', 'n.', '獅子', 'animals', '🦁', true, 1),
  (47, 'tiger', 'n.', '老虎', 'animals', '🐯', false, 2),
  (48, 'elephant', 'n.', '大象', 'animals', '🐘', false, 3),
  (49, 'monkey', 'n.', '猴子', 'animals', '🐵', false, 2),
  (50, 'frog', 'n.', '青蛙', 'animals', '🐸', true, 1),
  (51, 'snake', 'n.', '蛇', 'animals', '🐍', false, 2),
  (52, 'turtle', 'n.', '烏龜', 'animals', '🐢', false, 3),
  (53, 'bee', 'n.', '蜜蜂', 'animals', '🐝', true, 1),
  (54, 'ant', 'n.', '螞蟻', 'animals', '🐜', true, 1),
  (55, 'butterfly', 'n.', '蝴蝶', 'animals', '🦋', false, 3),
  (56, 'body', 'n.', '身體', 'body', '🧍', true, 1),
  (57, 'head', 'n.', '頭', 'body', '🙂', true, 1),
  (58, 'face', 'n.', '臉', 'body', '😀', true, 1),
  (59, 'hair', 'n.', '頭髮', 'body', '💇', true, 1),
  (60, 'eye', 'n.', '眼睛', 'body', '👁️', true, 1),
  (61, 'ear', 'n.', '耳朵', 'body', '👂', true, 1),
  (62, 'nose', 'n.', '鼻子', 'body', '👃', false, 2),
  (63, 'mouth', 'n.', '嘴巴', 'body', '👄', false, 2),
  (64, 'tooth', 'n.', '牙齒', 'body', '🦷', false, 2),
  (65, 'hand', 'n.', '手', 'body', '✋', true, 1),
  (66, 'arm', 'n.', '手臂', 'body', '💪', true, 1),
  (67, 'finger', 'n.', '手指', 'body', '👆', false, 2),
  (68, 'leg', 'n.', '腿', 'body', '🦵', true, 1),
  (69, 'foot', 'n.', '腳', 'body', '🦶', true, 1),
  (70, 'knee', 'n.', '膝蓋', 'body', '🦵', true, 1),
  (71, 'family', 'n.', '家庭', 'family', '👨‍👩‍👧', true, 2),
  (72, 'father', 'n.', '爸爸', 'family', '👨', true, 2),
  (73, 'mother', 'n.', '媽媽', 'family', '👩', true, 2),
  (74, 'brother', 'n.', '兄弟', 'family', '👦', true, 2),
  (75, 'sister', 'n.', '姊妹', 'family', '👧', true, 2),
  (76, 'grandfather', 'n.', '祖父', 'family', '👴', false, 3),
  (77, 'grandmother', 'n.', '祖母', 'family', '👵', false, 3),
  (78, 'son', 'n.', '兒子', 'family', '👦', true, 1),
  (79, 'daughter', 'n.', '女兒', 'family', '👧', false, 3),
  (80, 'uncle', 'n.', '叔叔；舅舅', 'family', '🧔', true, 2),
  (81, 'aunt', 'n.', '阿姨；姑姑', 'family', '👩', true, 1),
  (82, 'food', 'n.', '食物', 'food', '🍽️', true, 1),
  (83, 'fruit', 'n.', '水果', 'food', '🍇', true, 1),
  (84, 'apple', 'n.', '蘋果', 'food', '🍎', true, 1),
  (85, 'banana', 'n.', '香蕉', 'food', '🍌', false, 2),
  (86, 'grape', 'n.', '葡萄', 'food', '🍇', true, 1),
  (87, 'strawberry', 'n.', '草莓', 'food', '🍓', false, 3),
  (88, 'watermelon', 'n.', '西瓜', 'food', '🍉', false, 3),
  (89, 'tomato', 'n.', '番茄', 'food', '🍅', false, 2),
  (90, 'vegetable', 'n.', '蔬菜', 'food', '🥬', false, 3),
  (91, 'rice', 'n.', '米飯', 'food', '🍚', true, 1),
  (92, 'bread', 'n.', '麵包', 'food', '🍞', true, 1),
  (93, 'noodle', 'n.', '麵條', 'food', '🍜', false, 2),
  (94, 'egg', 'n.', '蛋', 'food', '🥚', true, 1),
  (95, 'soup', 'n.', '湯', 'food', '🍲', true, 1),
  (96, 'pizza', 'n.', '披薩', 'food', '🍕', false, 2),
  (97, 'hamburger', 'n.', '漢堡', 'food', '🍔', false, 3),
  (98, 'cake', 'n.', '蛋糕', 'food', '🍰', true, 1),
  (99, 'candy', 'n.', '糖果', 'food', '🍬', true, 1),
  (100, 'cookie', 'n.', '餅乾', 'food', '🍪', false, 2),
  (101, 'chocolate', 'n.', '巧克力', 'food', '🍫', false, 3),
  (102, 'ice cream', 'n.', '冰淇淋', 'food', '🍦', false, 3),
  (103, 'milk', 'n.', '牛奶', 'food', '🥛', true, 1),
  (104, 'water', 'n.', '水', 'food', '💧', false, 2),
  (105, 'juice', 'n.', '果汁', 'food', '🧃', true, 1),
  (106, 'tea', 'n.', '茶', 'food', '🍵', true, 1),
  (107, 'breakfast', 'n.', '早餐', 'food', '🌅', false, 3),
  (108, 'lunch', 'n.', '午餐', 'food', '🍱', true, 1),
  (109, 'dinner', 'n.', '晚餐', 'food', '🍽️', false, 2),
  (110, 'bowl', 'n.', '碗', 'tableware', '🥣', true, 1),
  (111, 'cup', 'n.', '杯子', 'tableware', '🥤', true, 1),
  (112, 'plate', 'n.', '盤子', 'tableware', '🍽️', true, 1),
  (113, 'spoon', 'n.', '湯匙', 'tableware', '🥄', false, 2),
  (114, 'fork', 'n.', '叉子', 'tableware', '🍴', true, 1),
  (115, 'chopsticks', 'n.', '筷子', 'tableware', '🥢', false, 3),
  (116, 'school', 'n.', '學校', 'school', '🏫', false, 2),
  (117, 'classroom', 'n.', '教室', 'school', '🪑', false, 3),
  (118, 'library', 'n.', '圖書館', 'school', '📚', false, 3),
  (119, 'playground', 'n.', '操場', 'school', '🛝', false, 3),
  (120, 'teacher', 'n.', '老師', 'school', '👩‍🏫', false, 3),
  (121, 'student', 'n.', '學生', 'school', '🧑‍🎓', false, 3),
  (122, 'classmate', 'n.', '同學', 'school', '👫', false, 3),
  (123, 'friend', 'n.', '朋友', 'school', '🧑‍🤝‍🧑', true, 2),
  (124, 'book', 'n.', '書', 'school', '📖', true, 1),
  (125, 'pen', 'n.', '原子筆', 'school', '🖊️', true, 1),
  (126, 'pencil', 'n.', '鉛筆', 'school', '✏️', false, 2),
  (127, 'eraser', 'n.', '橡皮擦', 'school', '🧽', true, 2),
  (128, 'ruler', 'n.', '尺', 'school', '📏', true, 1),
  (129, 'bag', 'n.', '書包', 'school', '🎒', true, 1),
  (130, 'desk', 'n.', '書桌', 'school', '🪑', true, 1),
  (131, 'homework', 'n.', '家庭作業', 'school', '📝', false, 3),
  (132, 'test', 'n.', '測驗', 'school', '📋', true, 1),
  (133, 'English', 'n.', '英文', 'school', '🔤', false, 3),
  (134, 'math', 'n.', '數學', 'school', '➗', true, 1),
  (135, 'music', 'n.', '音樂', 'school', '🎵', true, 1),
  (136, 'art', 'n.', '美術', 'school', '🎨', true, 1),
  (137, 'science', 'n.', '自然科學', 'school', '🔬', false, 3),
  (138, 'Monday', 'n.', '星期一', 'time', '📅', true, 3),
  (139, 'Tuesday', 'n.', '星期二', 'time', '📅', false, 3),
  (140, 'Wednesday', 'n.', '星期三', 'time', '📅', false, 3),
  (141, 'Thursday', 'n.', '星期四', 'time', '📅', false, 3),
  (142, 'Friday', 'n.', '星期五', 'time', '📅', true, 3),
  (143, 'Saturday', 'n.', '星期六', 'time', '📅', false, 3),
  (144, 'Sunday', 'n.', '星期日', 'time', '📅', false, 3),
  (145, 'January', 'n.', '一月', 'time', '🗓️', false, 3),
  (146, 'February', 'n.', '二月', 'time', '🗓️', false, 3),
  (147, 'March', 'n.', '三月', 'time', '🗓️', true, 2),
  (148, 'April', 'n.', '四月', 'time', '🗓️', true, 2),
  (149, 'May', 'n.', '五月', 'time', '🗓️', true, 2),
  (150, 'June', 'n.', '六月', 'time', '🗓️', true, 2),
  (151, 'July', 'n.', '七月', 'time', '🗓️', true, 2),
  (152, 'August', 'n.', '八月', 'time', '🗓️', true, 3),
  (153, 'September', 'n.', '九月', 'time', '🗓️', false, 3),
  (154, 'October', 'n.', '十月', 'time', '🗓️', false, 3),
  (155, 'November', 'n.', '十一月', 'time', '🗓️', false, 3),
  (156, 'December', 'n.', '十二月', 'time', '🗓️', false, 3),
  (157, 'spring', 'n.', '春天', 'time', '🌸', false, 3),
  (158, 'summer', 'n.', '夏天', 'time', '☀️', false, 3),
  (159, 'autumn', 'n.', '秋天', 'time', '🍁', true, 3),
  (160, 'winter', 'n.', '冬天', 'time', '❄️', false, 3),
  (161, 'morning', 'n.', '早上', 'time', '🌅', false, 3),
  (162, 'afternoon', 'n.', '下午', 'time', '🌇', false, 3),
  (163, 'night', 'n.', '晚上', 'time', '🌙', true, 2),
  (164, 'clothes', 'n.', '衣服', 'clothing', '👕', false, 3),
  (165, 'shirt', 'n.', '襯衫', 'clothing', '👔', true, 1),
  (166, 'T-shirt', 'n.', 'T恤', 'clothing', '👕', false, 3),
  (167, 'coat', 'n.', '外套', 'clothing', '🧥', true, 1),
  (168, 'jacket', 'n.', '夾克', 'clothing', '🧥', false, 2),
  (169, 'dress', 'n.', '洋裝', 'clothing', '👗', true, 1),
  (170, 'skirt', 'n.', '裙子', 'clothing', '👗', true, 1),
  (171, 'pants', 'n.', '長褲', 'clothing', '👖', true, 1),
  (172, 'shorts', 'n.', '短褲', 'clothing', '🩳', false, 2),
  (173, 'socks', 'n.', '襪子', 'clothing', '🧦', false, 2),
  (174, 'shoes', 'n.', '鞋子', 'clothing', '👟', true, 1),
  (175, 'hat', 'n.', '帽子', 'clothing', '👒', true, 1),
  (176, 'cap', 'n.', '鴨舌帽', 'clothing', '🧢', true, 1),
  (177, 'umbrella', 'n.', '雨傘', 'clothing', '☂️', false, 3),
  (178, 'weather', 'n.', '天氣', 'weather', '🌤️', false, 3),
  (179, 'sunny', 'adj.', '晴朗的', 'weather', '☀️', false, 3),
  (180, 'rainy', 'adj.', '下雨的', 'weather', '🌧️', false, 3),
  (181, 'cloudy', 'adj.', '多雲的', 'weather', '☁️', false, 3),
  (182, 'windy', 'adj.', '有風的', 'weather', '💨', false, 3),
  (183, 'hot', 'adj.', '熱的', 'weather', '🥵', true, 2),
  (184, 'cold', 'adj.', '冷的', 'weather', '🥶', true, 2),
  (185, 'warm', 'adj.', '溫暖的', 'weather', '🌡️', true, 2),
  (186, 'rain', 'n.', '雨', 'weather', '🌧️', true, 2),
  (187, 'snow', 'n.', '雪', 'weather', '❄️', true, 2),
  (188, 'wind', 'n.', '風', 'weather', '💨', true, 2),
  (189, 'cloud', 'n.', '雲', 'weather', '☁️', false, 3),
  (190, 'sun', 'n.', '太陽', 'weather', '☀️', true, 2),
  (191, 'moon', 'n.', '月亮', 'weather', '🌙', true, 2),
  (192, 'star', 'n.', '星星', 'weather', '⭐', true, 2),
  (193, 'rainbow', 'n.', '彩虹', 'weather', '🌈', false, 3),
  (194, 'bus', 'n.', '公車', 'transportation', '🚌', true, 1),
  (195, 'car', 'n.', '汽車', 'transportation', '🚗', true, 1),
  (196, 'train', 'n.', '火車', 'transportation', '🚆', true, 2),
  (197, 'taxi', 'n.', '計程車', 'transportation', '🚕', true, 1),
  (198, 'bicycle', 'n.', '腳踏車', 'transportation', '🚲', false, 3),
  (199, 'motorcycle', 'n.', '機車', 'transportation', '🏍️', false, 3),
  (200, 'airplane', 'n.', '飛機', 'transportation', '✈️', false, 3),
  (201, 'boat', 'n.', '小船', 'transportation', '🛶', true, 1),
  (202, 'truck', 'n.', '卡車', 'transportation', '🚚', true, 2),
  (203, 'station', 'n.', '車站', 'transportation', '🚉', false, 3),
  (204, 'airport', 'n.', '機場', 'transportation', '🛫', false, 3),
  (205, 'home', 'n.', '家', 'places', '🏠', true, 1),
  (206, 'park', 'n.', '公園', 'places', '🏞️', true, 1),
  (207, 'zoo', 'n.', '動物園', 'places', '🦓', true, 1),
  (208, 'store', 'n.', '商店', 'places', '🏪', false, 2),
  (209, 'market', 'n.', '市場', 'places', '🏬', false, 2),
  (210, 'supermarket', 'n.', '超級市場', 'places', '🛒', false, 3),
  (211, 'bank', 'n.', '銀行', 'places', '🏦', true, 1),
  (212, 'hospital', 'n.', '醫院', 'places', '🏥', false, 3),
  (213, 'restaurant', 'n.', '餐廳', 'places', '🍴', false, 3),
  (214, 'post office', 'n.', '郵局', 'places', '📮', false, 3),
  (215, 'bookstore', 'n.', '書店', 'places', '📚', false, 3),
  (216, 'beach', 'n.', '海灘', 'places', '🏖️', true, 1),
  (217, 'farm', 'n.', '農場', 'places', '🚜', true, 1),
  (218, 'city', 'n.', '城市', 'places', '🏙️', true, 1),
  (219, 'house', 'n.', '房子', 'house', '🏡', true, 1),
  (220, 'door', 'n.', '門', 'house', '🚪', true, 1),
  (221, 'window', 'n.', '窗戶', 'house', '🪟', false, 3),
  (222, 'room', 'n.', '房間', 'house', '🛋️', true, 1),
  (223, 'bedroom', 'n.', '臥室', 'house', '🛏️', false, 3),
  (224, 'bathroom', 'n.', '浴室', 'house', '🛁', false, 3),
  (225, 'kitchen', 'n.', '廚房', 'house', '🍳', false, 3),
  (226, 'bed', 'n.', '床', 'house', '🛏️', true, 1),
  (227, 'chair', 'n.', '椅子', 'house', '🪑', true, 1),
  (228, 'table', 'n.', '桌子', 'house', '🪑', true, 1),
  (229, 'key', 'n.', '鑰匙', 'house', '🔑', true, 1),
  (230, 'baseball', 'n.', '棒球', 'sports', '⚾', false, 3),
  (231, 'basketball', 'n.', '籃球', 'sports', '🏀', false, 3),
  (232, 'soccer', 'n.', '足球', 'sports', '⚽', true, 2),
  (233, 'badminton', 'n.', '羽毛球', 'sports', '🏸', false, 3),
  (234, 'swim', 'n.', '游泳', 'sports', '🏊', true, 1),
  (235, 'run', 'n.', '跑步', 'sports', '🏃', true, 1),
  (236, 'game', 'n.', '遊戲；比賽', 'sports', '🎮', true, 1),
  (237, 'dance', 'n.', '跳舞', 'sports', '💃', true, 1),
  (238, 'doctor', 'n.', '醫生', 'jobs', '👨‍⚕️', true, 3),
  (239, 'nurse', 'n.', '護理師', 'jobs', '👩‍⚕️', true, 2),
  (240, 'farmer', 'n.', '農夫', 'jobs', '👨‍🌾', false, 3),
  (241, 'cook', 'n.', '廚師', 'jobs', '👨‍🍳', true, 2),
  (242, 'driver', 'n.', '司機', 'jobs', '🚗', false, 3),
  (243, 'police', 'n.', '警察', 'jobs', '👮', false, 3),
  (244, 'singer', 'n.', '歌手', 'jobs', '🎤', false, 3),
  (245, 'worker', 'n.', '工人', 'jobs', '👷', false, 3),
  (246, 'clerk', 'n.', '店員', 'jobs', '🧑‍💼', true, 2),
  (247, 'happy', 'adj.', '快樂的', 'feelings', '😄', true, 2),
  (248, 'sad', 'adj.', '難過的', 'feelings', '😢', true, 2),
  (249, 'angry', 'adj.', '生氣的', 'feelings', '😠', true, 2),
  (250, 'afraid', 'adj.', '害怕的', 'feelings', '😨', false, 3),
  (251, 'tired', 'adj.', '疲倦的', 'feelings', '😴', true, 2),
  (252, 'excited', 'adj.', '興奮的', 'feelings', '🤩', false, 3),
  (253, 'bored', 'adj.', '無聊的', 'feelings', '😑', true, 2),
  (254, 'hungry', 'adj.', '飢餓的', 'feelings', '🍽️', false, 3),
  (255, 'thirsty', 'adj.', '口渴的', 'feelings', '🥤', false, 3),
  (256, 'sick', 'adj.', '生病的', 'feelings', '🤒', true, 2),
  (257, 'kind', 'adj.', '親切的', 'feelings', '🤗', true, 2),
  (258, 'eat', 'v.', '吃', 'verbs', '🍽️', true, 2),
  (259, 'drink', 'v.', '喝', 'verbs', '🥤', false, 3),
  (260, 'sleep', 'v.', '睡覺', 'verbs', '😴', false, 3),
  (261, 'walk', 'v.', '走路', 'verbs', '🚶', true, 2),
  (262, 'jump', 'v.', '跳', 'verbs', '🤸', true, 2),
  (263, 'sing', 'v.', '唱歌', 'verbs', '🎤', true, 2),
  (264, 'read', 'v.', '閱讀', 'verbs', '📖', true, 2),
  (265, 'write', 'v.', '寫', 'verbs', '✍️', false, 3),
  (266, 'draw', 'v.', '畫', 'verbs', '🎨', true, 2),
  (267, 'play', 'v.', '玩', 'verbs', '🎮', true, 2),
  (268, 'go', 'v.', '去', 'verbs', '➡️', true, 2),
  (269, 'come', 'v.', '來', 'verbs', '⬅️', true, 2),
  (270, 'look', 'v.', '看', 'verbs', '👀', true, 2),
  (271, 'listen', 'v.', '聽', 'verbs', '👂', false, 3),
  (272, 'speak', 'v.', '說', 'verbs', '🗣️', false, 3),
  (273, 'learn', 'v.', '學習', 'verbs', '🧠', false, 3),
  (274, 'teach', 'v.', '教', 'verbs', '👩‍🏫', false, 3),
  (275, 'help', 'v.', '幫助', 'verbs', '🤝', true, 2),
  (276, 'open', 'v.', '打開', 'verbs', '🔓', true, 2),
  (277, 'close', 'v.', '關上', 'verbs', '🔒', true, 2),
  (278, 'buy', 'v.', '買', 'verbs', '🛍️', true, 2),
  (279, 'give', 'v.', '給', 'verbs', '🎁', true, 2),
  (280, 'make', 'v.', '製作', 'verbs', '🔨', true, 2),
  (281, 'like', 'v.', '喜歡', 'verbs', '👍', true, 2),
  (282, 'love', 'v.', '愛', 'verbs', '❤️', true, 2),
  (283, 'big', 'adj.', '大的', 'adjectives', '🐘', true, 2),
  (284, 'small', 'adj.', '小的', 'adjectives', '🐜', false, 3),
  (285, 'long', 'adj.', '長的', 'adjectives', '📏', true, 2),
  (286, 'short', 'adj.', '短的；矮的', 'adjectives', '📐', false, 3),
  (287, 'tall', 'adj.', '高的', 'adjectives', '🦒', true, 2),
  (288, 'new', 'adj.', '新的', 'adjectives', '✨', true, 2),
  (289, 'old', 'adj.', '舊的；老的', 'adjectives', '👴', true, 2),
  (290, 'good', 'adj.', '好的', 'adjectives', '👍', true, 2),
  (291, 'bad', 'adj.', '壞的', 'adjectives', '👎', true, 2),
  (292, 'fast', 'adj.', '快的', 'adjectives', '⚡', true, 2),
  (293, 'slow', 'adj.', '慢的', 'adjectives', '🐌', true, 2),
  (294, 'beautiful', 'adj.', '美麗的', 'adjectives', '🌺', false, 3),
  (295, 'what', 'pron.', '什麼', 'wh-words', '❓', true, 2),
  (296, 'who', 'pron.', '誰', 'wh-words', '❓', true, 2),
  (297, 'where', 'pron.', '哪裡', 'wh-words', '📍', true, 3),
  (298, 'when', 'pron.', '什麼時候', 'wh-words', '🕐', true, 2),
  (299, 'why', 'pron.', '為什麼', 'wh-words', '❓', true, 2),
  (300, 'how', 'pron.', '如何', 'wh-words', '❓', true, 2)
on conflict (id) do update set
  word = excluded.word, pos = excluded.pos, zh = excluded.zh,
  theme = excluded.theme, emoji = excluded.emoji,
  spell = excluded.spell, level = excluded.level;

-- 商店品項。**這一段是 tools/gen-shop-seed.mjs 從 src/data/shop.ts 產生的，不要手改。**
-- 價格放在資料庫是因為客戶端送來的價格不能信。
insert into public.shop_items (id, price, kind, slot, unlock_level, achievement_only, free, need_achievement) values
  ('slow-30', 60, 'consumable', null, 1, false, false, null),
  ('heal-5', 80, 'consumable', null, 2, false, false, null),
  ('crystal-40', 120, 'consumable', null, 3, false, false, null),
  ('color-red', 1, 'cosmetic', 'color', 1, false, true, null),
  ('color-yellow', 1, 'cosmetic', 'color', 1, false, true, null),
  ('color-purple', 1, 'cosmetic', 'color', 1, false, true, null),
  ('color-black', 1, 'cosmetic', 'color', 1, false, true, null),
  ('legion-goblin', 300, 'cosmetic', 'legion', 3, false, false, null),
  ('legion-pig', 600, 'cosmetic', 'legion', 6, false, false, 'top-tier'),
  ('legion-pirate-bomb', 300, 'cosmetic', 'legion', 3, false, false, null),
  ('legion-treasure', 300, 'cosmetic', 'legion', 3, false, false, null),
  ('legion-monsters', 300, 'cosmetic', 'legion', 3, false, false, null),
  ('legion-elementals', 1000, 'cosmetic', 'legion', 10, false, false, null),
  ('av-monk-m', 300, 'cosmetic', 'avatar', 1, false, false, null),
  ('av-monk-f', 300, 'cosmetic', 'avatar', 1, false, false, null),
  ('av-ranger-m', 300, 'cosmetic', 'avatar', 1, false, false, null),
  ('av-ranger-f', 300, 'cosmetic', 'avatar', 1, false, false, null),
  ('av-ninja-m', 300, 'cosmetic', 'avatar', 1, false, false, null),
  ('av-ninja-f', 300, 'cosmetic', 'avatar', 1, false, false, null),
  ('av-berserk-m', 300, 'cosmetic', 'avatar', 1, false, false, null),
  ('av-berserk-f', 300, 'cosmetic', 'avatar', 1, false, false, null),
  ('av-pirate', 300, 'cosmetic', 'avatar', 1, false, false, null),
  ('av-merchant', 300, 'cosmetic', 'avatar', 1, false, false, null),
  ('av-bard', 300, 'cosmetic', 'avatar', 1, false, false, null),
  ('av-samurai-m', 800, 'cosmetic', 'avatar', 4, false, false, null),
  ('av-samurai-f', 800, 'cosmetic', 'avatar', 4, false, false, null),
  ('av-dknight-m', 800, 'cosmetic', 'avatar', 4, false, false, null),
  ('av-dknight-f', 800, 'cosmetic', 'avatar', 4, false, false, null),
  ('av-paladin', 800, 'cosmetic', 'avatar', 4, false, false, null),
  ('av-dancer', 800, 'cosmetic', 'avatar', 4, false, false, null),
  ('av-captain', 800, 'cosmetic', 'avatar', 4, false, false, null),
  ('av-vampire', 800, 'cosmetic', 'avatar', 4, false, false, null),
  ('av-el-fire', 1500, 'cosmetic', 'avatar', 8, false, false, null),
  ('av-el-water', 1500, 'cosmetic', 'avatar', 8, false, false, null),
  ('av-el-wind', 1500, 'cosmetic', 'avatar', 8, false, false, null),
  ('av-el-earth', 1500, 'cosmetic', 'avatar', 8, false, false, null),
  ('av-el-light', 1500, 'cosmetic', 'avatar', 8, false, false, null),
  ('av-el-dark', 1500, 'cosmetic', 'avatar', 8, false, false, null),
  ('av-angel', 1500, 'cosmetic', 'avatar', 8, false, false, null),
  ('av-king', 1500, 'cosmetic', 'avatar', 8, false, false, null),
  ('av-queen', 1500, 'cosmetic', 'avatar', 8, false, false, null),
  ('frame-gold', 120, 'cosmetic', 'frame', 1, false, false, null),
  ('frame-ribbon', 180, 'cosmetic', 'frame', 3, false, false, null),
  ('frame-crown', 260, 'cosmetic', 'frame', 5, false, false, null),
  ('frame-rainbow', 400, 'cosmetic', 'frame', 7, false, false, null),
  ('frame-laurel', 1, 'cosmetic', 'frame', 1, true, false, null),
  ('frame-wave', 1, 'cosmetic', 'frame', 1, true, false, null),
  ('frame-flame', 1, 'cosmetic', 'frame', 1, true, false, null),
  ('frame-banner', 1, 'cosmetic', 'frame', 1, true, false, null),
  ('frame-stardust', 1, 'cosmetic', 'frame', 1, true, false, null),
  ('frame-calendar', 1, 'cosmetic', 'frame', 1, true, false, null),
  ('frame-boss-mimic', 1, 'cosmetic', 'frame', 1, true, false, null),
  ('frame-boss-minotaur', 1, 'cosmetic', 'frame', 1, true, false, null),
  ('frame-boss-worm', 1, 'cosmetic', 'frame', 1, true, false, null),
  ('frame-boss-king', 1, 'cosmetic', 'frame', 1, true, false, null),
  ('frame-boss-wizard', 1, 'cosmetic', 'frame', 1, true, false, null),
  ('frame-boss-cthulhu', 1, 'cosmetic', 'frame', 1, true, false, null),
  ('frame-boss-demon', 1, 'cosmetic', 'frame', 1, true, false, null),
  ('frame-boss-frost', 1, 'cosmetic', 'frame', 1, true, false, null),
  ('frame-boss-shadow', 1, 'cosmetic', 'frame', 1, true, false, null),
  ('frame-boss-lich', 1, 'cosmetic', 'frame', 1, true, false, null)
on conflict (id) do update
  set price = excluded.price, kind = excluded.kind, slot = excluded.slot,
      unlock_level = excluded.unlock_level, achievement_only = excluded.achievement_only,
      free = excluded.free, need_achievement = excluded.need_achievement;

-- 商店只認這份清單。舊品項留在資料庫裡會變成「買得到但畫面上沒有」的鬼品項，
-- 所以不在清單裡的一律刪掉。
delete from public.shop_items where id not in ('slow-30', 'heal-5', 'crystal-40', 'color-red', 'color-yellow', 'color-purple', 'color-black', 'legion-goblin', 'legion-pig', 'legion-pirate-bomb', 'legion-treasure', 'legion-monsters', 'legion-elementals', 'av-monk-m', 'av-monk-f', 'av-ranger-m', 'av-ranger-f', 'av-ninja-m', 'av-ninja-f', 'av-berserk-m', 'av-berserk-f', 'av-pirate', 'av-merchant', 'av-bard', 'av-samurai-m', 'av-samurai-f', 'av-dknight-m', 'av-dknight-f', 'av-paladin', 'av-dancer', 'av-captain', 'av-vampire', 'av-el-fire', 'av-el-water', 'av-el-wind', 'av-el-earth', 'av-el-light', 'av-el-dark', 'av-angel', 'av-king', 'av-queen', 'frame-gold', 'frame-ribbon', 'frame-crown', 'frame-rainbow', 'frame-laurel', 'frame-wave', 'frame-flame', 'frame-banner', 'frame-stardust', 'frame-calendar', 'frame-boss-mimic', 'frame-boss-minotaur', 'frame-boss-worm', 'frame-boss-king', 'frame-boss-wizard', 'frame-boss-cthulhu', 'frame-boss-demon', 'frame-boss-frost', 'frame-boss-shadow', 'frame-boss-lich');


-- 成就目錄。**這一段是 tools/gen-achievements-seed.mjs 從 src/data/achievements.ts
-- 產生的，不要手改。** 名字與說明在 TS 那邊，這裡只有伺服器算解鎖要用的欄位。
insert into public.achievements (id, category, ord, reward_item, reward_title, tiers, reward_tier) values
  ('first-answer', 'learn', 0, null, '新生', '{}', 1),
  ('hundred', 'learn', 1, null, '', '{100,500,1000,3000,10000}', 1),
  ('nemesis', 'learn', 2, null, '不放棄', '{1,5,15,30,60}', 1),
  ('theme-king', 'learn', 3, null, '', '{3,5,10,15,-1}', 1),
  ('mastered-50', 'learn', 4, null, '', '{50,250,500,750,-1}', 1),
  ('literate', 'learn', 5, 'frame-laurel', '', '{50,100,200,250,-1}', 5),
  ('read-100', 'skill', 6, null, '', '{100,300,1000,2000,5000}', 1),
  ('listen-100', 'skill', 7, null, '', '{100,300,1000,2000,5000}', 1),
  ('spell-100', 'skill', 8, null, '', '{100,300,1000,2000,5000}', 1),
  ('triple-day', 'skill', 9, null, '', '{1,5,15,30,60}', 1),
  ('long-words', 'skill', 10, null, '', '{10,30,80,150,300}', 1),
  ('balanced', 'skill', 11, 'frame-wave', '', '{20,50,100,150,-1}', 2),
  ('combo', 'skill', 12, null, '', '{10,20,30,40,50}', 1),
  ('first-clear', 'tower', 13, null, '', '{}', 1),
  ('three-star', 'tower', 14, null, '', '{1,3,7,10,-1}', 1),
  ('no-damage', 'tower', 15, null, '', '{1,3,7,10,-1}', 1),
  ('boss-slayer', 'tower', 16, null, '', '{}', 1),
  ('stars-30', 'tower', 17, null, '', '{5,15,25,35,-1}', 1),
  ('all-clear', 'tower', 18, 'frame-flame', '', '{}', 1),
  ('first-match', 'versus', 19, null, '', '{}', 1),
  ('veteran', 'versus', 20, null, '', '{5,20,50,100,200}', 1),
  ('all-lines', 'versus', 21, null, '', '{}', 1),
  ('top-tier', 'versus', 22, null, '', '{1,5,15,30,60}', 1),
  ('comeback', 'versus', 23, null, '', '{1,3,10,20,40}', 1),
  ('never-quit', 'versus', 24, null, '再來一局', '{}', 1),
  ('war-flag', 'versus', 25, 'frame-banner', '', '{5,15,40,80,150}', 1),
  ('first-live', 'coop', 26, null, '', '{}', 1),
  ('live-mates', 'coop', 27, null, '', '{3,5,10,15,20}', 1),
  ('raid-slayer', 'coop', 28, null, '', '{1,3,5,8,-1}', 1),
  ('raid-wins', 'coop', 29, null, '', '{1,5,15,30,60}', 1),
  ('big-team', 'coop', 30, null, '', '{1,3,10,20,40}', 1),
  ('raid-mates', 'coop', 31, null, '', '{3,5,10,15,20}', 1),
  ('dressed', 'collect', 32, null, '', '{}', 1),
  ('five-colors', 'collect', 33, null, '', '{}', 1),
  ('all-frames', 'collect', 34, null, '', '{}', 1),
  ('avatar-10', 'collect', 35, null, '', '{}', 1),
  ('dual-job', 'collect', 36, 'frame-stardust', '', '{}', 1),
  ('item-taster', 'collect', 37, null, '', '{}', 1),
  ('week-3', 'habit', 38, null, '', '{}', 1),
  ('days', 'habit', 39, null, '', '{7,20,40,70,100}', 1),
  ('weekend', 'habit', 40, null, '', '{1,5,15,30,50}', 1),
  ('replay', 'habit', 41, null, '', '{}', 1),
  ('month-12', 'habit', 42, null, '', '{}', 1),
  ('old-friend', 'habit', 43, null, '', '{}', 1),
  ('week-5', 'habit', 44, 'frame-calendar', '', '{}', 1),
  ('persistent', 'secret', 45, null, '', '{}', 1),
  ('quick-hand', 'secret', 46, null, '', '{}', 1),
  ('so-close', 'secret', 47, null, '', '{}', 1),
  ('bare-handed', 'secret', 48, null, '', '{}', 1),
  ('combo-20', 'secret', 49, null, '', '{}', 1),
  ('all-rounder', 'secret', 50, null, '全能生', '{}', 1)
on conflict (id) do update
  set category = excluded.category, ord = excluded.ord,
      reward_item = excluded.reward_item, reward_title = excluded.reward_title,
      tiers = excluded.tiers, reward_tier = excluded.reward_tier;

-- 目錄以這份清單為準。刪掉的成就要跟著消失，不然畫面上沒有、資料庫裡卻還在，
-- 別人的徽章牆上會冒出一個誰都看不懂的東西。
delete from public.achievements where id not in ('first-answer', 'hundred', 'nemesis', 'theme-king', 'mastered-50', 'literate', 'read-100', 'listen-100', 'spell-100', 'triple-day', 'long-words', 'balanced', 'combo', 'first-clear', 'three-star', 'no-damage', 'boss-slayer', 'stars-30', 'all-clear', 'first-match', 'veteran', 'all-lines', 'top-tier', 'comeback', 'never-quit', 'war-flag', 'first-live', 'live-mates', 'raid-slayer', 'raid-wins', 'big-team', 'raid-mates', 'dressed', 'five-colors', 'all-frames', 'avatar-10', 'dual-job', 'item-taster', 'week-3', 'days', 'weekend', 'replay', 'month-12', 'old-friend', 'week-5', 'persistent', 'quick-hand', 'so-close', 'bare-handed', 'combo-20', 'all-rounder');


-- 關卡。**這一段是 tools/gen-levels-seed.mjs 從 src/data/levels.ts 產生的，不要手改。**
-- min_correct 是「這一關至少要答對幾題才可能通關」，通關與星星由伺服器判定時要用。
insert into public.levels (id, no, name, min_correct, is_boss) values
  ('td-01', 1, '數字島', 13, false),
  ('td-02', 2, '顏色與身體', 15, false),
  ('td-03', 3, '動物森林', 17, false),
  ('td-04', 4, '食物與餐具', 24, false),
  ('td-05', 5, '衣櫃魔王', 14, true),
  ('td-06', 6, '我家', 15, false),
  ('td-07', 7, '學校', 16, false),
  ('td-08', 8, '出門去', 18, false),
  ('td-09', 9, '運動與職業', 19, false),
  ('td-10', 10, '暴風雨魔王', 18, true),
  ('td-11', 11, '心情', 18, false),
  ('td-12', 12, '動起來', 20, false),
  ('td-13', 13, '時間之塔', 21, false),
  ('td-14', 14, '最終試煉', 28, true)
on conflict (id) do update
  set no = excluded.no, name = excluded.name, min_correct = excluded.min_correct,
      is_boss = excluded.is_boss;

commit;
